module.exports={
    assets:{
        expand:true,
        cwd:'./assets',
        src:'**',
        dest:'./build<%= asset_dir %>'
    },
    CryptoJS:{
        src:'website/js/CryptoJS.js',
        dest:'website/build/CryptoJS.js'
    },
    sdk:{
        src:'website/js/sdk.js',
        dest:'website/build/sdk.js'
    },
    cognitoSdk:{
        src:'website/js/cognito.js',
        dest:'website/build/cognito.js'
    }
}
