module.exports={
    lambda:{
        files:[
            {expand:true,src:["lambda/*/tmp/*_latest.zip"],dest:"tmp"}
        ]
    },
    cloudformation:{
        files:[
            {expand:true,src:["cloudformation/*/tmp/CF-*.json"],dest:"tmp"}
        ]
    }
}
