module.exports={
    lambda:{
        files:[
            {expand:true,src:["lambda/*/tmp/*_latest.zip"],dest:"tmp",flatten:true}
        ]
    },
    cloudformation:{
        files:[
            {
                expand:true,
                src:["cloudformation/*/tmp/CF-*.json"],
                dest:"tmp",
                flatten:true}
        ]
    },
    sql:{
        files:[
            {expand:true,src:["lambda/LambdAuth/tmp/auth.sql"],dest:"data/scripts",flatten:true}
        ]
    }
}
