module.exports={
    createcognitopool:{
        files:{
            "lambda/CreateCognitoPool/build/handler.js":['lambda/CreateCognitoPool/handler.js'],
            "lambda/CreateCognitoPool/build/process.js":['lambda/CreateCognitoPool/process.js'],
            "lambda/CreateCognitoPool/build/response.js":['lambda/CreateCognitoPool/response.js'],
            "lambda/CreateCognitoPool/build/cognito.js":['lambda/CreateCognitoPool/cognito.js']
        }
    },
    createcognitoidentity:{
        files:{
            "lambda/CreateCognitoIdentity/build/handler.js":['lambda/CreateCognitoIdentity/handler.js'],
            "lambda/CreateCognitoIdentity/build/process.js":['lambda/CreateCognitoIdentity/process.js'],
            "lambda/CreateCognitoIdentity/build/response.js":['lambda/CreateCognitoIdentity/response.js']
        }
    },
    client:{
        files:{
            "build/timing.js":["client/timing.js"]
        }
    }
}

