module.exports={
    createcognitopool:{
        files:{
            "lambda/CreateCognitoPool/build/handler.js":['lambda/CreateCognitoPool/handler.js'],
            "lambda/CreateCognitoPool/build/process.js":['lambda/CreateCognitoPool/process.js'],
            "lambda/CreateCognitoPool/build/response.js":['lambda/CreateCognitoPool/response.js'],
            "lambda/CreateCognitoPool/build/cognito.js":['lambda/CreateCognitoPool/cognito.js']
        }
    },
    createswfactivity:{
        files:{
            "lambda/CreateSWFActivity/build/handler.js":['lambda/CreateSWFActivity/handler.js'],
            "lambda/CreateSWFActivity/build/process.js":['lambda/CreateSWFActivity/process.js'],
            "lambda/CreateSWFActivity/build/response.js":['lambda/CreateSWFActivity/response.js'],
            "lambda/CreateSWFActivity/build/swf.js":['lambda/CreateSWFActivity/swf.js']
        }
    },
    createswfworkflow:{
        files:{
            "lambda/CreateSWFWorkFlow/build/handler.js":['lambda/CreateSWFWorkFlow/handler.js'],
            "lambda/CreateSWFWorkFlow/build/process.js":['lambda/CreateSWFWorkFlow/process.js'],
            "lambda/CreateSWFWorkFlow/build/response.js":['lambda/CreateSWFWorkFlow/response.js'],
            "lambda/CreateSWFWorkFlow/build/swf.js":['lambda/CreateSWFWorkFlow/swf.js']
        }
    },
    createswfdomain:{
        files:{
            "lambda/CreateSWFDomain/build/handler.js":['lambda/CreateSWFDomain/handler.js'],
            "lambda/CreateSWFDomain/build/process.js":['lambda/CreateSWFDomain/process.js'],
            "lambda/CreateSWFDomain/build/response.js":['lambda/CreateSWFDomain/response.js'],
            "lambda/CreateSWFDomain/build/swf.js":['lambda/CreateSWFDomain/swf.js']
        }
    },
    createcognitoidentity:{
        files:{
            "lambda/CreateCognitoIdentity/build/handler.js":['lambda/CreateCognitoIdentity/handler.js'],
            "lambda/CreateCognitoIdentity/build/process.js":['lambda/CreateCognitoIdentity/process.js'],
            "lambda/CreateCognitoIdentity/build/response.js":['lambda/CreateCognitoIdentity/response.js'],
            "lambda/CreateCognitoIdentity/build/cognito.js":['lambda/CreateCognitoIdentity/cognito.js']
        }
    },
    createhealthcheck:{
        files:{
            "lambda/CreateHealthCheck/build/handler.js":['lambda/CreateHealthCheck/handler.js'],
            "lambda/CreateHealthCheck/build/process.js":['lambda/CreateHealthCheck/process.js'],
            "lambda/CreateHealthCheck/build/response.js":['lambda/CreateHealthCheck/response.js']
        }
    },
    client:{
        files:{
            "build/timing.js":["client/timing.js"]
        }
    }
}

