module.exports={
    rdsproxy:{
        files:{
            "lambda/RDSProxy/build/handler.js":['lambda/RDSProxy/handler.js']
        }
    },
    createcognitopool:{
        files:{
            "lambda/CreateCognitoPool/build/handler.js":['lambda/CreateCognitoPool/handler.js'],
            "lambda/CreateCognitoPool/build/process.js":['lambda/CreateCognitoPool/process.js'],
            "lambda/CreateCognitoPool/build/response.js":['lambda/CreateCognitoPool/response.js'],
            "lambda/CreateCognitoPool/build/cognito.js":['lambda/CreateCognitoPool/cognito.js']
        }
    },
    createcognitoidentity:{
        files:{
            "lambda/CreateCognitoIdentity/build/handler.js":['lambda/CreateCognitoIdentity/handler.js'],
            "lambda/CreateCognitoIdentity/build/process.js":['lambda/CreateCognitoIdentity/process.js'],
            "lambda/CreateCognitoIdentity/build/response.js":['lambda/CreateCognitoIdentity/response.js'],
            "lambda/CreateCognitoIdentity/build/cognito.js":['lambda/CreateCognitoIdentity/cognito.js']
        }
    },
    initdatabase:{
        files:{
            "lambda/InitDataBase/build/handler.js":['lambda/InitDataBase/handler.js'],
            "lambda/InitDataBase/build/process.js":['lambda/InitDataBase/process.js'],
            "lambda/InitDataBase/build/response.js":['lambda/InitDataBase/response.js']
        }
    },
    createhealthcheck:{
        files:{
            "lambda/CreateHealthCheck/build/handler.js":['lambda/CreateHealthCheck/handler.js'],
            "lambda/CreateHealthCheck/build/process.js":['lambda/CreateHealthCheck/process.js'],
            "lambda/CreateHealthCheck/build/response.js":['lambda/CreateHealthCheck/response.js']
        }
    },
    CryptoJS:{
        options:{
            mangle:false
        },
        files:{
            "website/js/CryptoJS.js":["tmp/CryptoJS.tmp.js"]
        }
    },      
    sdk:{
        options:{
            mangle:false
        },
        files:{
            "website/js/sdk.js":["tmp/sdk.tmp.js"]
        }
    },    
    dist:{
        files:{
            "website/build/main.js":["tmp/main.js"]
        }
    },
    cognitoSdk:{
        files:{
            "tmp/jsbn.min.js":["tmp/jsbn.js"],
            "tmp/jsbn2.min.js":["tmp/jsbn2.js"]
        }
    }
}

